version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
      - "5678:5678"
    depends_on:
      - db
    volumes:
      - ./web:/usr/src/app  # Mount local code directory into the container
  db:
    build: ./db
    
